"""Assemble the one-file report: event study + backtest, figures + tables.

Runs offline on the committed golden fixtures by default, so `reproduce.sh`
works on a clean checkout. Point --posts/--prices at fetched data for the full
report.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from trumptailer import core
from trumptailer.nlp.classifier import classify_posts
from trumptailer.nlp.schema import events_to_frame
from trumptailer.ingest.prices import daily_frame_to_store
from trumptailer.ingest.truth_archive import TruthArchiveAdapter
from trumptailer.research.align import align_posts, build_event_locations
from trumptailer.research.signals import baseline_scores
from trumptailer.research.universe import load_universe
from trumptailer.research.walk_forward import deflated_over_configs
from trumptailer.viz import plots

_ROOT = Path(__file__).resolve().parents[3]
_GOLDEN_POSTS = _ROOT / "data" / "golden" / "truth_sample.parquet"
_GOLDEN_PRICES = _ROOT / "data" / "golden" / "prices_daily.parquet"


def _load_store(prices_path: Path, cal):
    store = core.BarStore()
    for symbol, g in pd.read_parquet(prices_path).groupby("symbol"):
        daily_frame_to_store(store, cal, symbol, g.set_index("date").sort_index())
    return store


def build_report(outdir: Path, posts_path: Path = _GOLDEN_POSTS,
                 prices_path: Path = _GOLDEN_PRICES) -> dict:
    outdir.mkdir(parents=True, exist_ok=True)
    universe = load_universe()
    cal = core.TradingCalendar()
    store = _load_store(prices_path, cal)

    posts = TruthArchiveAdapter(str(posts_path)).to_frame()
    events = align_posts(events_to_frame(classify_posts(posts, universe)), cal)

    # Event study: tariff events on the most tariff-sensitive name we have bars for.
    tariff = events[(events["category"] == "TariffTrade") & (events["instrument"] == "AAPL")]
    es_cfg = core.EventStudyConfig(est_start=-60, est_end=-5, car_start=0, car_end=6)
    syms, idx = build_event_locations(tariff, store)
    es = core.event_study(syms, idx, store, universe.benchmark, es_cfg)

    car_png = plots.plot_car(es, "Tariff posts -> AAPL abnormal return vs SPY", outdir / "car.png")
    decay_png = plots.plot_alpha_decay(es, outdir / "alpha_decay.png")

    # Backtest across all classified events, deflated over holding-period configs.
    all_syms, all_idx = build_event_locations(events, store)
    scores = baseline_scores(events)
    configs = [core.BacktestConfig(holding_bars=h) for h in (1, 2, 3, 5)]
    summary = deflated_over_configs(all_syms, all_idx, scores, store, configs)
    bt = core.backtest(all_syms, all_idx, scores, store,
                       core.BacktestConfig(holding_bars=summary["best_holding_bars"]))
    eq_png = plots.plot_equity(bt, outdir / "equity.png")

    report_md = outdir / "report.md"
    is_golden = Path(posts_path).resolve() == _GOLDEN_POSTS.resolve()
    report_md.write_text(
        _render_markdown(es, summary, bt, car_png, decay_png, eq_png, is_golden)
    )
    return {"report": report_md, "car": car_png, "alpha_decay": decay_png, "equity": eq_png}


def _render_markdown(es, summary, bt, car_png, decay_png, eq_png, is_golden) -> str:
    dsr = summary["deflated_sharpe"]
    dsr_str = "n/a (too few trades)" if dsr != dsr else f"{dsr:.3f}"
    n_trades = summary["n_trades"]

    if is_golden:
        provenance = (
            "The figures below are from the committed **golden fixture** (the "
            "April 2025 'Liberation Day' window), so this report reproduces on "
            "any clean checkout. Point `--posts/--prices` at fetched data for the "
            "full sample."
        )
    else:
        provenance = (
            f"The figures below are from the **full fetched sample** (event-study "
            f"N = {es.n}; {n_trades} backtest trades). Re-run without `TT_FETCH=1` "
            f"for the offline golden-fixture version."
        )

    # Interpretability keys off the actual N, not the data source (invariant #3).
    if n_trades < 30:
        n_note = (
            f"**N is small ({n_trades} trades)** — the deflated Sharpe is "
            f"intentionally not interpretable here; it becomes meaningful only on "
            f"the full archive."
        )
    else:
        n_note = (
            f"**N = {n_trades} trades**, so the deflated Sharpe is interpretable — "
            f"but at this sample size statistical significance does *not* imply "
            f"economic significance; judge the edge by the net Sharpe and costs "
            f"above, not the t-stat alone."
        )

    return f"""# TrumpTailer — Results

> Generated by `python -m trumptailer.viz.report`. {provenance}

## 1. Do tariff posts move a tariff-sensitive stock?

Market-model event study (estimation window ends strictly before the event;
entry strictly after the after-close announcement):

- **CAAR over [0, +{es.offsets[-1]}] = {es.caar_total * 100:.2f}%**, t = {es.t_caar:.2f}, **N = {es.n}**

![CAR]({car_png.name})

![Alpha decay]({decay_png.name})

## 2. Does it survive costs? (backtest, net)

All classified events, deflated across {summary['n_trials']} holding-period configs:

| metric | value |
|---|---|
| best holding (days) | {summary['best_holding_bars']} |
| gross Sharpe | {summary['gross_sharpe']} |
| net Sharpe | {summary['net_sharpe']} |
| deflated Sharpe | {dsr_str} |
| trades (N) | {summary['n_trades']} |

![Equity]({eq_png.name})

## 3. Honesty notes

- {n_note}
- All headline returns are **net of transaction costs and latency**.
- Events are **selected by the classifier over the full post stream**, never
  hand-picked. Estimation windows never overlap the event (no look-ahead).
"""


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--posts", type=Path, default=_GOLDEN_POSTS)
    ap.add_argument("--prices", type=Path, default=_GOLDEN_PRICES)
    ap.add_argument("--outdir", type=Path, default=_ROOT / "reports")
    args = ap.parse_args()
    out = build_report(args.outdir, args.posts, args.prices)
    print(f"report -> {out['report']}")


if __name__ == "__main__":
    main()
